includes:
  - secrets.yaml

runtime: nodejs20

env_variables:
  DB_USER: "confidant"
  DB_PASS: "3108"
  DB_NAME: "wellofsecrets"
  CLOUD_SQL_CONNECTION_NAME: "well-of-secrets:europe-west1:well-of-secrets-db"

beta_settings:
  cloud_sql_instances: "well-of-secrets:europe-west1:well-of-secrets-db"

